### ISSUE TITLE
Error when using ctx.bot.send_message when the receiver is groupID.

### ISSUE THREAD

**Issue by brazuzan** [lwesterhof/semaphore#35]
I'm trying to forward a message from a group to another. So, I'm using ChatContext.bot.send_message(). Problem is that the parameter receiver only seems to work if it is a phone number or a uuid. When I try to pass a groupID it doesn't work. Am I missing something?

This is the error I'm seeing:
```
Traceback (most recent call last):
  File "/home/user/PycharmProjects/Tutorials/venv/lib/python3.9/site-packages/semaphore/bot.py", line 109, in _handle_message
    await func(context)
  File "/home/user/PycharmProjects/Tutorials/main.py", line 27, in echo
    await ctx.bot.send_message(
  File "/home/user/PycharmProjects/Tutorials/venv/lib/python3.9/site-packages/semaphore/bot.py", line 192, in send_message
    return await self._sender.send_message(receiver, body, attachments)
  File "/home/user/PycharmProjects/Tutorials/venv/lib/python3.9/site-packages/semaphore/message_sender.py", line 96, in send_message
    response = response_wrapper['data']
KeyError: 'data'
```

**Comment by brazuzan** [comment]
Solved by editing the code #36.
